### PR TITLE
Start screen

### PR DESCRIPTION
**Pull request by Shom770**
The start screen will be in the beginning, there are two controls, (s) to start the game, (h) for how to play the game, and more may come in the future,
after pressing (s) a progress "bar" will pop up (it is mostly fake and just cosmetic so I can remove it)

### CODE REVIEW

**Comment by Shom770** [comment]
Blessed support hasn't been added yet but the start screen is finished!

**Comment by Antsthebul** [comment]
This is awesome. This display of the name seems a bit off depending on the size of the terminal

**Review by Antsthebul — APPROVED** [review]
I think this is good for now. Better than weirdly wrapped text

**Review by cons01e — APPROVED** [review]
I love it! The color and theme are great! The only thing I would add is a way to get back to the start screen from the help screen.

**Pull request merged**
